# Site
name: "Davi Backendorf"
title: "Davi Backendorf"
description: "Magento Developer"
logo: 'assets/images/cup.png'
favicon: 'assets/images/cup.png'
baseurl: "/"
google_analytics: 'UA-192077938-1'
disqus: 'davi-backendorf-blog'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
google_site_verification: '5h-B7uGZrSiAJMXJwn3niulqOB1F0GMnUrLnmBZVtZo'

# Authors
authors:
  davi:
    name: Davi Backendorf
    display_name: Davi Backendorf
    gravatar: 1e278b22d91673996a42e397f59e904b
    email: davijacksonb@gmail.com
    web: /
    # twitter: https://twitter.com/wowthemesnet
    description: "Magento developer"
 
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]


linkedin_url: "https://www.linkedin.com/in/davibackendorf" 
